### ISSUE TITLE
Equipment List Layout

### ISSUE THREAD

**Issue by Caesir** [semuer/XIUtilsEquipCalculator#6]
TO-DO
Add gear piece on selected set slot when click on.
Adjust the position of "select" and "gear info text". Other layout-related issues I will talk to you in detail on QQ then >.>

![image](https://user-images.githubusercontent.com/56148974/117564728-0d770980-b0e0-11eb-91f2-9c4e9d19e9ae.png)

**Comment by semuer** [comment]
Continues in https://github.com/semuer/XIUtilsEquipCalculator/issues/33
