### ISSUE TITLE
Remove Currently Selected Gear Piece

### ISSUE THREAD

**Issue by Caesir** [semuer/XIUtilsEquipCalculator#7]
TO-DO
Add "remove" button on the set to cancel the currently selected one(s) in that slot when mouse over

![image](https://user-images.githubusercontent.com/56148974/117564857-bde50d80-b0e0-11eb-8e0c-aa675b3a388e.png)

**Comment by semuer** [comment]
Implemented in 0f5272bd131c03b09fc2ea4e0eea170da038ae39
